name: Build and upload executables to release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pylon-cli
            asset_name: pylon-cli-linux
          - os: macos-latest
            artifact_name: pylon-cli
            asset_name: pylon-cli-macos
          - os: windows-latest
            artifact_name: pylon-cli.exe
            asset_name: pylon-cli-windows.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.release.tag_name }}
